const alphabetData = [
  { letter: 'A', words: ['Apple', 'Ant', 'Axe', 'Airplane', 'Arrow'] },
  { letter: 'B', words: ['Ball', 'Bat', 'Bee', 'Book', 'Bell'] },
  { letter: 'C', words: ['Cat', 'Car', 'Cup', 'Cow', 'Cake'] },
  { letter: 'D', words: ['Dog', 'Duck', 'Dolphin', 'Diamond', 'Dragon'] },
  { letter: 'E', words: ['Elephant', 'Egg', 'Earth', 'Eagle', 'Envelope']},
  { letter: 'F', words: ['Fox', 'Frog', 'Fish', 'Flamingo', 'Fire'] },
  { letter: 'G', words: ['Goat', 'Gorilla', 'Grape', 'Giraffe', 'Globe'] },
  { letter: 'H', words: ['Horse', 'Hat', 'House', 'Heart', 'Hamburger'] },
  { letter: 'I', words: ['Iguana', 'Ice', 'Island', 'Igloo', 'Iron'] },
  { letter: 'J', words: ['Jaguar', 'Jellyfish', 'Jacket', 'Jar', 'Jet'] },
  { letter: 'K', words: ['Kangaroo', 'Kite', 'Key', 'King', 'Koala'] },
  { letter: 'L', words: ['Lion', 'Lemon', 'Laptop', 'Lamp', 'Leaf'] },
  { letter: 'M', words:  ['Monkey', 'Moon', 'Mango', 'Mountain', 'Mailbox'] },
  { letter: 'N', words: ['Nest', 'Noodle', 'Ninja', 'Notebook', 'Necklace'] },
  { letter: 'O', words: ['Owl', 'Orange', 'Octopus', 'Ocean', 'Oven'] },
  { letter: 'P', words: ['Penguin', 'Pizza', 'Pear', 'Parrot', 'Painting'] },
  { letter: 'Q', words: ['Quail', 'Queen', 'Quilt', 'Quote', 'Quartz'] },
  { letter: 'R', words: ['Rabbit', 'Rainbow', 'Rose', 'Rocket', 'Raccoon'] },
  { letter: 'S', words: ['Snake', 'Star', 'Sun', 'Ship', 'Snowflake'] },
  { letter: 'T', words: ['Tiger', 'Turtle', 'Tree', 'Teapot', 'Trumpet'] },
  { letter: 'U', words:  ['Unicorn', 'Umbrella', 'Underwear', 'Utensils', 'Uniform'] },
  { letter: 'V', words:  ['Vampire', 'Volcano', 'Violin', 'Vase', 'Vegetable'] },
  { letter: 'W', words: ['Wolf', 'Watermelon', 'Whale', 'Wagon', 'Watch'] },
  { letter: 'X', words: ['Xylophone', 'X-ray', 'Xenon', 'Xerographica', 'Xenopus'] },
  { letter: 'Y', words: ['Yak', 'Yacht', 'Yogurt', 'Yoyo', 'Yellow'] },
  { letter: 'Z', worDs: ['Zebra', 'Zoo', 'Zip', 'Zero', 'Zigzag'] },
];

export default alphabetData;
